#!/usr/bin/env bash
# Interactive one-time setup for the daily IMAP report.
# - Prompts (silently) for your StartMail app password.
# - Writes ~/.config/daily-report/imap.cfg with mode 600.
# - Installs the crontab entry (23:59 local daily).
# - Offers to do a test send so you can confirm Thunderbird sees the message
#   before relying on the cron.

set -euo pipefail

CONFIG_DIR="$HOME/.config/daily-report"
CONFIG_FILE="$CONFIG_DIR/imap.cfg"
SCRIPT="$HOME/.claude-config/scripts/daily_report.py"
LOG_FILE="$HOME/.local/share/daily-report.log"

# Defaults — change these if your StartMail account or address differs.
DEFAULT_SERVER="imap.startmail.com"
DEFAULT_PORT="993"
DEFAULT_USERNAME="pbhwheeler@startmail.com"
DEFAULT_TO="pbhwheeler@startmail.com"
DEFAULT_FROM="pbhwheeler@startmail.com"
CRON_TIME="59 23 * * *"  # 23:59 local daily

cat <<EOF
=== Daily report setup ===

This will write your StartMail app-password to:
  $CONFIG_FILE  (mode 600)

and install a crontab entry that runs the daily report at 23:59 local time.

App passwords are managed at StartMail Settings → Security → Application
passwords. Generate a fresh one for this purpose so you can revoke it
independently if needed.

EOF

# Prompt for the app password, silently
prompt_password() {
  local pw pw2
  while :; do
    printf "StartMail app password: "
    stty -echo
    IFS= read -r pw
    stty echo
    echo
    if [ -z "$pw" ]; then
      echo "  (empty — try again)"
      continue
    fi
    printf "Re-enter to confirm:    "
    stty -echo
    IFS= read -r pw2
    stty echo
    echo
    if [ "$pw" = "$pw2" ]; then
      APP_PASSWORD="$pw"
      return
    fi
    echo "  (mismatch — try again)"
  done
}

# Allow non-default username override
read -p "Username (default: $DEFAULT_USERNAME): " username
username="${username:-$DEFAULT_USERNAME}"

read -p "To address  (default: $DEFAULT_TO):       " to_addr
to_addr="${to_addr:-$DEFAULT_TO}"

read -p "From address (default: $DEFAULT_FROM):     " from_addr
from_addr="${from_addr:-$DEFAULT_FROM}"

prompt_password

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

# Write atomically so a partial write can't corrupt an existing config
tmp="$(mktemp -p "$CONFIG_DIR" .imap.XXXXXX)"
chmod 600 "$tmp"
cat >"$tmp" <<EOF
# Daily report IMAP credentials — generated by setup_daily_report.sh
# Mode 600. Do not commit this file.
imap_server = $DEFAULT_SERVER
imap_port = $DEFAULT_PORT
username = $username
password = $APP_PASSWORD
to_address = $to_addr
from_address = $from_addr
EOF
mv "$tmp" "$CONFIG_FILE"
echo
echo "Wrote $CONFIG_FILE (mode $(stat -c '%a' "$CONFIG_FILE"))"

# Install crontab line if not already present.
# Match by referencing the daily_report.py path — survives time-of-day edits.
mkdir -p "$(dirname "$LOG_FILE")"
existing_cron="$(crontab -l 2>/dev/null || true)"
cron_line="$CRON_TIME $SCRIPT >> $LOG_FILE 2>&1"

if printf '%s\n' "$existing_cron" | grep -qF "$SCRIPT"; then
  echo "Crontab already references $SCRIPT — not modified. Current line(s):"
  printf '%s\n' "$existing_cron" | grep -F "$SCRIPT" | sed 's/^/  /'
else
  ( printf '%s\n' "$existing_cron"; printf '%s\n' "$cron_line" ) | crontab -
  echo "Installed crontab entry:"
  echo "  $cron_line"
fi

echo
read -p "Send a test report now to verify everything works? [Y/n] " yn
yn="${yn:-Y}"
case "$yn" in
  [Yy]*)
    echo "Running: $SCRIPT --test"
    "$SCRIPT" --test
    echo
    echo "Check Thunderbird's Inbox and Sent folder for a message with subject"
    echo "starting 'Daily report —'. May take a few seconds for the IMAP refresh."
    ;;
  *)
    echo "Skipped test send. Run manually anytime:"
    echo "  $SCRIPT --test       # send now"
    echo "  $SCRIPT --dry-run    # build report, print only"
    ;;
esac

echo
echo "Done."
